### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by shaundasmith** [skiptomyliu/milkshake#36] opened 2019-05-13 12:48 UTC
The volume on my computer for everything else works fine, but for some reason, the sound has completely stopped on my Milkshake app!

**Comment by mattley43** [comment] 2019-05-14 18:54
I've had the same issue. Tried on multiple machines, restarts, reinstalls, output changes. Nothing changes it. Also, I do not see the volume control that was supposed to have come out in Dec 2018.

**Comment by chuckwigand** [comment] 2019-05-15 13:30
Same issue here.  Just started yesterday out of the blue after working great since downloading.

**Comment by tyrahat** [comment] 2019-05-15 17:53
Same, upgraded Mac to 10.14.4 and no sound from App. Found a forum which said to rollback AdobeAir to 31 but that's blocked by my company, so if this is the fix, then no more Milkshake for me :(

**Comment by djzednaught** [comment] 2019-05-17 19:28
Aye.  Same problem here.  Using Version 1.0.9 (35) on MacOS 10.11.6 and just nothing anymore.  Everything else seems to work fine.  Loved the app so hopefully we'll see a resolution soon.

**Comment by charles-evans** [comment] 2019-05-20 17:20
Same here.  AdobeAir wasn't installed but installing 31 didn't seem to help either.

**Comment by tyrahat** [comment] 2019-05-23 19:17
Fixed by changing the settings in my browser, I use FF so this is what I had to do and works fine now!
    Click the menu button and open the Preferences menu.
    Select the Privacy and Security panel.
    Scroll down to Permissions.
    Find the Block websites from automatically playing setting, and select Exceptions. 
    Under Allowed Websites add https://www.pandora.com and set the status to Allow.
    Select Save Changes and refresh your page.

**Comment by skiptomyliu** [comment] 2019-06-02 14:22
Not a good experience I know -- but I haven't been able to nail down the problem unfortunately.  

This sucks to advise, but can you create a new account and see if the problem resolves?  This seems to be on an account by account basis where there might be a configuration setting on Pandora's server that is preventing Milkshake from playing the music.  This _seems_ to sometimes self resolve itself also after some time.

Hoping to reproduce it soon so I can come out with some sort of fix for this.

**Comment by shaundasmith** [comment] 2019-06-02 14:33
For some reason, mine just started working again!!!

**Comment by skiptomyliu** [comment] 2019-06-02 14:59
@mattley43 the volume control is on the now playing screen.  Put your mouse cursor over the cover art and it should reveal itself:


<img width="412" alt="Screen Shot 2019-06-02 at 7 57 47 AM" src="https://user-images.githubusercontent.com/3451399/58763151-23e7b400-850c-11e9-99e6-13ecb53bb196.png">

However, if you don't hear any music playing, the volume control isn't going to work anyway :\  because Milkshake doesn't persist volume settings across restarts (it defaults to 100% volume).  I'd try a new account temporarily to see if it works while I figure out how to reproduce this issue.

**Comment by Alacron** [comment] 2019-07-27 21:43
Volume not working on milkshake player. Using Safari browser. The settings suggested in the thread are not available in Safari settings. Removed and reinstalled, still not working. Any assistance with this matter will be appreciated.

**Comment by skiptomyliu** [comment] 2019-07-29 20:07
@Alacron , can you post a screenshot of what you're experiencing?

Also, can you elaborate on how you're using Safari?  This desktop client doesn't use Safari for volume, but is encapsulated in its own player.

**Comment by Alacron** [comment] 2019-07-30 04:19
Nothing really shows in a screenshot. The milkshake app shows thumbnails of your play list with an animated equalizer indicating the selection is playing - but no sound. I referenced Safari in my original message because I read a post where the problem was corrected by manipulating Firefox settings.

Thank you for getting back to me tho. 



			Alaric B Lofton
			252.640.4539 (W)
			252.305.1967 (C)
			252.654.9321 (F)
			alariclofton@gmail.com

**Comment by skiptomyliu** [comment] 2019-07-30 14:08
@Alacron are you using the paid Pandora Premium by chance?  Pandora recently updated their API which seems to have broken the Premium on-demand playing.  I spent an afternoon trying to resolve this, but unfortunately wasn't able to.

Does Radio Stations within Pandora still work by chance?

**Comment by Alacron** [comment] 2019-07-30 18:35
I am using a paid version of pandora, and I thank you for your time with this matter. I was planning to look into it this weekend - when I had a little time to investigate.  But the internet works so I will settle for that right now.
Again, thank you for your efforts



			Alaric B Lofton
			252.640.4539 (W)
			252.305.1967 (C)
			252.654.9321 (F)
			alariclofton@gmail.com

**Comment by skiptomyliu** [comment] 2019-07-31 16:49
@Alacron , gotcha -- yeah no volume on playlists and on-demand playing for paid Pandora Premium users.  Unfortunately this is a known issue at the moment.  

Radio stations should still work.

There were some security restrictions recently added (I think within the past month or so) to the API that unfortunately has broken the Milkshake client 😭   

I'm not quite sure if I'll be able to figure it out sometime soon 😞

**Comment by saramccombs** [comment] 2019-07-31 19:28
@skiptomyliu Thanks for the updates. I ran into this particular issue a day or so ago. But didn't recognize that the issue was isolated to my playlists as I rarely play them. 

Since you did not get clarification regarding whether stations still work. I can confirm, at least for myself as a Pandora Premium subscriber, that the issue is indeed isolated to playlists as stations will play without volume issues.

**Comment by skiptomyliu** [comment] 2019-08-02 03:05
Thanks for the clarification and confirmation that this is isolated to playlists and on-demand play.

**Comment by skiptomyliu** [comment] 2022-08-15 21:13
Pandora Premium has been resolved in the most recent release.

Closing out!  Let's reopen if ther eare still issues.

**Closed by skiptomyliu** 2022-08-15 21:13 UTC
Labels: bug
